### ISSUE TITLE
Allow multiple xib children

### ISSUE THREAD

**Issue by thejeff77** [mobilejazz/NibWrapper#5]
This library seems to only support one xib as a child object. This limits the library's capabilities. Can you support multiple child xibs?

**Comment by vilanovi** [comment]
What do you mean by multiple child xibs? Feel free to write code as your proposal and submit a pull request.

**Comment by thejeff77** [comment]
Well, I was struggling with some nibs in a nested UIView in my project not showing up, and I figured out that I should use a container/content view that has a separate UIViewController in it which houses the nibs. I also ran across this library, although it only works for a single nib, not a collection of nibs & constraints that a UIViewController would have. Its me re-learning how to do layout in iOS. I'll close this request for now, as there are better standardized ways of doing what I needed to do.
